### ISSUE TITLE
Support ghc-8.4

### ISSUE THREAD

**Issue by harendra-kumar** [kapralVV/Unique#1]

**Comment by kapralVV** [comment]
@harendra-kumar 
Merged to master, Thanks a lot. I'll be happy to see new pull requests from you in future.

**Comment by carlosdagos** [comment]
@kapralVV, thanks for merging #2, have you had a chance to upload the revision of the cabal file to http://hackage.haskell.org/package/Unique-0.4.7.2/revisions/ ? 

Would be great :) Thanks!

**Comment by kapralVV** [comment]
@carlosdagos  I'm going to upload a new release package soon. (maybe tomorrow or the day after ) 
Thanks
