### ISSUE TITLE
Unique is not uniq

### ISSUE THREAD

**Issue by juhp** [kapralVV/Unique#4]
Sorry to complain but unique is basically similar to nub, not to uniq at all.

Unix uniq drops _consecutive_ duplicates in list, not all duplicates! 
That is quite different, though useful.

**Comment by kapralVV** [comment]
>Unix uniq drops consecutive duplicates in list, not all duplicates!'
That's right. 'unique' function in this library like 'sort --unique' or nub . This is written in documentation and have examples. 
Do you have suggestions or patches / pull requests ? You may add 'uniq' function that behaves as 'unix uniq' exactly

**Comment by juhp** [comment]
Ah, sorry: I was referring to the synopsis in the .cabal file...

**Comment by kapralVV** [comment]
>Ah, sorry: I was referring to the synopsis in the .cabal file...
It's ok. 
> Yea would be nice to add a uniq function.
uniq :: Eq a => [a] -> [a]
uniq = map (head) . Data.List.group

**Comment by juhp** [comment]
I could send a patch for the synopsis but I am not sure how best to reword it.
Maybe adding `uniq` is easier, thanks :-)

**Comment by juhp** [comment]
Are you going to add `uniq`? :-)

**Comment by kapralVV** [comment]
@juhp 
Yep, maybe later. Need to write tests for it as well. This requires some time I do not have. 
Yo

**Comment by kapralVV** [comment]
@juhp I've just added it without tests .

**Comment by juhp** [comment]
Thanks a lot!!
